// pages/api/hellocoop.ts
// generated by @hellocoop/quickstart --nextjs on 2023-12-24T21:11:02.317Z
// this file should not need to be edited
import config from '../../hello.config'
import { pageAuth } from '@hellocoop/nextjs'
export default pageAuth(config)
